### ISSUE TITLE
Progress Report of Students.

### ISSUE THREAD

**Issue by amarkrsinha1997** [navgurukul/galileo#74]
This feature would help the mentors and other students to view the progress of their peers so they can view who is stuck where? Who needs help and from whom they can seek help.

## Part I
**Understanding Mentors**
- table `mentors` - mentor, and mentee columns

**Understanding Facilitators**
- facilitator across a center
- Rishabh facilitator for Dharamsala, Abhishek facilitator for Bangalore

## Part 2
** Student Progress**
User: facilitator/mentor
- Should be able to view the Student Progress
    - Course Specific
    - Across all courses
- Can mark `course` as complete (add a column in course_enrolments table) (think of it as a course_status table)

API:
  **/reports/course/[courseId]** to get report for all my students for a specific course
  **/reports/courses** to get report for all my students for all courses
  **/courses/complete/[courseId]** to complete the course for student

**Comment by abhishekgupta92** [comment]
- students don't need to request facilitator for completion of the course through saral. they will request offline if they want

- He could see the required details to view the student.
(Average time of last 10 submission).
Days he spent in that course.
His he to slow?
All of his exercise.

Not needed in the first implementation. It should be as simple as possible. Let's do the MVP and launch asap. 

- Only report for students for whom I am the mentor should be shown

- Let's not use the facilitator role here - but "mentor" role here instead. Let facilitator be as it is... we will work on that role later

**Comment by abhishekgupta92** [comment]
[Notes.pdf](https://github.com/navgurukul/galileo/files/2723785/Notes.pdf)

Design Example

**Comment by amarkrsinha1997** [comment]
The facilitator should be able to view the progress of all students in a center? @abhishekgupta92 
The students shall be available to view their peer report under the same mentor?

# Todo:
## DB changes.
- [x] Remove facilitator and isAlumni from the user's table.
- [x] Add facilitator and Alumni in user_roles and center(Dharamshala, Bangalore, all) column.
- [x] Remove enrolled and course completed from course_enrolments.
- [x] Add course_status(enrolled, unenrolled, completed), enrolledAt and completedAt.
- [x] Add all the queries in the issues.

## Routes Updates.
- [x] Update enrolledInCourse route with course_status=enrolled on post.
- [x] Update the enrollled courses with submissionType != null in getCoursesList.
- [x] Add condition exercises submissionType != null in totalExercise for enrolled courses in getCoursesList.
- [x] Add courses which are completed by Student in getCoursesList.
- [x] Update the facilitatorId to get from user_roles and users table instead of courses in postExerciseSubmission.
- [x]  Refactor loginUser.
- [x] Remove getting facilitator and isAlumni in the loginUser.
- [x] Update getting facilitator from user_roles in loginUser.
- [x] get courses Report shall contain the totalExercises number which doesn't have the submissionType null.
- [x] get courses report shall only retrieve the submissions of the exercises which has submissionType in it. Write the query to get the submissionType.
- [x] Make the routes for reports restful.
- [x] create course complete route.
## Other Changes
- [x] Change the logic of getting facilitator from courses to user_roles in seed-courses.
- [x] Change the schema of loginUser.
- [x] change the schema of getCourseList.
- [x] change the schema of getCoursesReport.
- [x] change the schema of getCourseReport.
- [ ] Needs to test loginUser.

**Comment by amarkrsinha1997** [comment]
For updating the facilitator and alumni roles

```mysql 
ALTER TABLE users DROP COLUMN facilitator;
ALTER TABLE users DROP COLUMN isAlumni;
ALTER TABLE user_roles CHANGE roles roles ENUM('students', 'facilitators', 'admin', 'alumni', 'student', 'facilitator') DEFAULT 'student';
UPDATE user_roles SET roles='student' WHERE roles='students';
ALTER TABLE user_roles CHANGE roles roles ENUM('admin', 'alumni', 'student', 'facilitator') DEFAULT 'student';
ALTER TABLE user_roles ADD COLUMN center ENUM('dharamshala','banagalore', 'all') DEFAULT NULL;
ALTER TABLE user_roles DROP INDEX userId;
```

**Comment by amarkrsinha1997** [comment]
For updating the course_enrollment
```mysql
ALTER TABLE course_enrolments DROP COLUMN enrolled;
ALTER TABLE course_enrolments DROP COLUMN completed;
ALTER TABLE course_enrolments ADD COLUMN courseStatus ENUM('enroll', 'unenroll', 'completed') DEFAULT 'enroll';
ALTER TABLE course_enrolments ADD COLUMN completedAt datetime DEFAULT NULL;
```

**Comment by amarkrsinha1997** [comment]
For the table, courses need to remove the concept the facilitator per courses.
```mysql
ALTER TABLE courses DROP FOREIGN KEY course_fac;
ALTER TABLE courses DROP COLUMN facilitator ;
```

**Comment by amarkrsinha1997** [comment]
**/reports/courses**
- [x] Facilitator would have all the student of his/her center as his/her mentees.
- [x] If a person is not a facilitator then check if he/she is a mentor or not?
- [x] Test for the expectation failed.

**/reports/courses/39**
- [x] Facilitator would have all the student of his/her center as his/her mentees.
- [x] If a person is not a facilitator then check if he/she is a mentor or not?
- [x] Test for the expectation failed.
- [x] Only exercises with submissionType not null would be counted.

**/auth/google/login**
- [x] if he is removed from the facilitator from the config file and is still facilitator then remove him.
- [x] update the user_roles each time when someone login.

**Comment by amarkrsinha1997** [comment]
Mentor table 
```mysql 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `mentors` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `mentor` int(11) unsigned DEFAULT NULL,
  `mentee` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `mentor_ibfk_1_idx` (`mentor`),
  KEY `mentor_ibfk_2_idx` (`mentee`),
  CONSTRAINT `mentors_ibfk_1` FOREIGN KEY (`mentor`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `mentors_ibfk_2` FOREIGN KEY (`mentee`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
```

**Comment by amarkrsinha1997** [comment]
- [x] send the course details also with its exercises.

**Comment by amarkrsinha1997** [comment]
Need to check if this is working or not.
